class ElementsTabLinks:
    HOST = "https://demoqa.com"
    TEXTBOX_PAGE = f"{HOST}/text-box"
    CHECKBOX_PAGE = f"{HOST}/checkbox"
    RADIO_BUTTON_PAGE = f"{HOST}/radio-button"
    WEBTABLES_PAGE = f"{HOST}/webtables"
    BUTTONS_PAGE = f"{HOST}/buttons"
    LINKS_PAGE = f"{HOST}/links"
    BROKEN_LINKS_PAGE = f"{HOST}/broken"
    UPLDWNLD_PAGE = f"{HOST}/upload-download"
    DYNAMIC_PROPERTIES_PAGE = f"{HOST}/dynamic-properties"